name: Build TontiDette APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - run: tar -xzf tontidette.tar.gz
    
    - name: Voir ce qu'il y a après unzip
      run: ls -la
    
    - name: Voir à l'intérieur des dossiers
      run: ls -la */
