name: Build TontiDette APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - run: tar -xzf tontidette.tar.gz
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Chercher gradlew et compiler
      run: |
        GRADLEW=$(find . -name gradlew -type f | head -1)
        chmod +x $GRADLEW
        DIR=$(dirname $GRADLEW)
        cd $DIR
        ./gradlew assembleRelease
    
    - uses: actions/upload-artifact@v4
      with:
        name: TontiDette-Release-APK
        path: '**/app/build/outputs/apk/release/*.apk'
